image: lycantropos/cmake

stages:
  - build
  - test

cache:
  paths:
    - "build/*"

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_FLAGS="-march=native" ..
    - cmake --build .

test:
  stage: test
  script:
    - cd build/test
    - ctest